### ISSUE TITLE
Changing doSurvey.html

### ISSUE THREAD

**Issue by RDCarleton** [jonmenard007/SYSC4806-Project#102]
Currently, there is one page to display surveys that display all three buttons (edit, answer, close). It does not make sense for anyone but the survey creator to edit and close the survey.
Therefore, we should discuss whether to have two views, one for surveys you manage and one for answering a survey. Or another alternative such as changing the controllers to check the ID of the user accessing the survey.

**Comment by RDCarleton** [comment]
Created a branch (authenticate-user) that solves this. Will create PR after the meeting on Monday as this requires an update in the DB tables.

**Comment by Jacoblab1** [comment]
Sounds good @RDCarleton! Look forward to testing out your PR after the Monday meeting.
