### ISSUE TITLE
Weekly scrum - [April 3 - 9]

### ISSUE THREAD

**Issue by jonmenard** [jonmenard007/SYSC4806-Project#115]
### Jon Menard
**what have I done this week?**
> 
| Description | Pull requests|
| -- | -- |
| Added Statistical Analysis of Surveys, once they are closed  | #109    
| Changed display user's surveys template, to link to their surveys | #113 | 
| Added name and description to surveys, changed template and controllers to match  | #119  | 
| Refactored redundant code, fixed some survey bugs | #121 | 
| Added added ability to edit questions bounds and choices  | #123 | 
| Added Integration testing for all the repositories  | #125, #126 | 
| Changed the database structure, to remove a many to many table | #125  | 

**what will I do next week?**
> Next week we will be focusing on continuing to integrate Kafka into our system

**what is holding me back?**
> Nothing, our team is communicating great, and the project is almost complete

**Comment by pauliwag** [comment]
## Paul Roode

***What have I done this week?***

<table>
    <thead>
        <tr>
            <th align="left"> Description </th>
            <th align="left" width="14%"> Pull requests </th>
            <th align="left" width="14%"> Linked issues </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan="3"> Added an error controller and view, and updated integration tests accordingly </td>
            <td> #98 </td>
            <td> #99 </td>
        </tr>
        <tr></tr>
        <tr>
            <td> #104 </td>
            <td> #99 </td>
        </tr>
        <tr>
            <td> Integrated the log-on page into the landing page, and revamped the landing page UI using Semantic UI </td>
            <td> #104 </td>
            <td> #103 </td>
        </tr>
        <tr>
            <td> Bugfix re: duplicate user registration </td>
            <td> #104 </td>
            <td> #105 </td>
        </tr>
        <tr>
            <td> Revamped the displayAllOpenSurveys and displayUserSurveys UIs using Semantic UI </td>
            <td> #98 </td>
            <td> #100 </td>
        </tr>
    </tbody>
</table>

[Click here to see my contributions in the first week of this sprint.](https://github.com/jonmenard007/SYSC4806-Project/issues/92#issue-848839858)

---

***What will I do next week?***

- Work on the oral presentation on Kafka.

---

***What is holding me back?***

Nothing – the team has done well to regularly communicate on Discord and coordinate on incrementally developing and validating the required components.

**Comment by RDCarleton** [comment]
### Rohil Dubey
**what have I done this week?**
> - Updated SurveyController to link Survey and EndUser during creation (#95)
> - Added unit tests for EndUser, updated Javadoc for model classes (#96)
> - Created common method for log message creation (#114)
> - Added check for EndUser to access survey edit options (#116)
> - Added additional ITMock tests and logs for survey edits (#127)
> - Added UML for milestone 3 (#128)



**what will I do next week?**
> Add onto the existing Kafka work for a complete presentation. 

**what is holding me back?**
> Nothing, everyone communicates frequently and if an issue occurs they thoroughly describe it so it can be resolved at the earliest.

**Comment by Jacoblab1** [comment]
### Jacob Laboissonniere
**what have I done this week?**
> - Added an Application Controller to handle shared @ModelAttribute items (#95)
> - Improved login functionality by implementing a user session cookie, along with an integration test for the login functionality (#95)
> - Modified templates that used a <form> element to submit GET requests to just use <a> links (#124)
> - Added ability for users to copy a shareable link to their survey (#124 / #132)
> - Added a "Thank you for your response" page + integration test for it (#124)
> - Added checks to verify that the current user is the owner of a Survey before displaying "Add Answer" or "Close Survey" buttons (#124)


**what will I do next week?**
> Will work on our oral presentation about Kafka

**what is holding me back?**
> Not much - just a busy time in the semester, so the workload with other courses has been heavy. Would have liked to have more time to improve this project even more. It has come a long way!
