### ISSUE TITLE
Helper method naming

### ISSUE THREAD

**Issue by Jacoblab1** [jonmenard007/SYSC4806-Project#16]
Just had a thought about the naming of the setAnswer() function:

Question subclasses currently implement the function setAnswer(). Perhaps this should be named addAnswer(), as that falls more in line with what the method actually does (adds an answer to the list of answers). setAnswer() makes it seem as though a Question can only have one answer. 

What do you guys think? A small change but I think it would make things more clear.

**Comment by pauliwag** [comment]
> Just had a thought about the naming of the setAnswer() function:
> 
> Question subclasses currently implement the function setAnswer(). Perhaps this should be named addAnswer(), as that falls more in line with what the method actually does (adds an answer to the list of answers). setAnswer() makes it seem as though a Question can only have one answer.
> 
> What do you guys think? A small change but I think it would make things more clear.

Hi @Jacoblab1.  I agree that `addAnswer()` would be a better name for the method, as a Question comprises multiple answers and there is no singular `answer` field.
