### ISSUE TITLE
Weekly scrum - [March 5 - March 12]

### ISSUE THREAD

**Issue by jonmenard** [jonmenard007/SYSC4806-Project#23]
### Jon Menard
**what have I done this week?**
> Added PostgreSQL to Heroku and set up a connection on the codebase side. Modified to POM.xml to match the version of spring boot to the version of PostgreSQL on Heroku. Fixed a few errors with the order of packaging for codebase configuration. 

**what will I do next week?**
> I will be writing the SQL insert and select statements and methods and using Thymeleaf to add support on the front end

**what is holding me back?**
> Currently I am testing the connection on the database and making sure everything is working correctly, once I know that is working properly I can move to the next step

**Comment by RDCarleton** [comment]
### Rohil Dubey
**what have I done this week?**
> Added first draft UML class diagram for the program models. Implemented base model along with unit testers. Added repository classes for the Question objects. 

**what will I do next week?**
> Begin work on the user portion of this program. This includes selecting an open survey and answering it. Will also assist in front end of HTML files. 

**what is holding me back?**
> Once the survey creation is implemented to a usable state, we can begin discussions on how to implement the answer functionality.

**Comment by Jacoblab1** [comment]
### Jacob Laboissonniere
**what have I done this week?**
> Worked on adding Javadocs to document our models. Implemented feature and tests closed survey state functionality. Reviewed pull requests from other team members, and added some Github issues regarding things that were discovered while updating documentation.

**what will I do next week?**
> Work on some front-end development to clean up the user flow. Ensure that our backend models and controllers can handle everything that our frontend requires. Improve documentation by continuing to add Javadocs and potentially some more UML diagrams.

**what is holding me back?**
> The initial setup of the project boilerplate was a bit difficult to collaborate on, but now that the team has that initial setup stage complete, I think building on top of it will be more straightforward.

**Comment by pauliwag** [comment]
## Paul Roode

***What have I done this week?***

<table>
    <thead>
        <tr>
            <th align="left"> Description </th>
            <th align="left" width="15%"> Pull requests </th>
            <th align="left" width="15%"> Linked issues </th>
        </tr>
    </thead>
    <tbody>
        <tr rowspan="2">
            <td> Finalized/optimized all of the models' object models </td>
            <td> #25 </td>
            <td> #27 </td>
        </tr>
        <tr>
            <td> Implemented controllers for Survey and all Question subtypes </td>
            <td> #11 </td>
            <td> #9 </td>
        </tr>
        <tr>
            <td rowspan="3"> Finalized the repository layer </td>
            <td> #25 </td>
            <td> #26 </td>
        </tr>
        <tr></tr>
        <tr>
            <td> #10 </td>
            <td> #8 </td>
        </tr>
        <tr>
            <td> Fixed a number of bugs to get the application running properly </td>
            <td> #13 </td>
            <td> #14 </td>
        </tr>
        <tr>
            <td> Formatted the README </td>
            <td> #28 </td>
            <td> #29 </td>
        </tr>
    </tbody>
</table>

---

***What will I do next week?***

- Further flesh out the controller layer in support of database operations as required by the front end.
- Fully implement a service layer.
- Investigate the incorporation of Kafka into the project.
- Update views, scripts (e.g., Ajax), models, and tests accordingly.

---

***What is holding me back?***

Nothing - the team has done well to regularly communicate on Discord and coordinate on incrementally developing and validating the required components.
