### ISSUE TITLE
Weekly scrum - [March 12 - March 19]

### ISSUE THREAD

**Issue by RDCarleton** [jonmenard007/SYSC4806-Project#40]
### Jon Menard
**what have I done this week?**
>  

| Description | Pull requests|
| -- | -- |
| Added Integration testing | #44  
| Fixed a naming collision in PostgreSQL by changing name of user table | #44 | 
| Added support to select what type of question to add to survey (text,number,select) | #46| 
| Added a new view to allow upper and lower bounds of number question to be changed | #47| 
| Added new controller mappings to allow upper and lower bounds of number question to be changed | #47| 

**what will I do next week?**
> Next week I will continue implementing the vertical slicing of question types. Number questions are almost done, however select question has not been started 

**what is holding me back?**
> Earlier in the week we were having trouble with PostgreSQL, now that that is sorted out right now it is just a matter of implementing things.  

### Jacob Laboissonniere
**what have I done this week?**
> Busy week with other classes, but did some work locally on the ability to fill out a survey (and save its answers in the database).

**what will I do next week?**
> Will continue to work on fleshing out the ability to fill surveys, and will also work to ensure that they can be closed (and then no more responses are allowed).

**what is holding me back?**
> Had some other work that needed to take priority. Will be able to catch up and complete the features I'm working on in the coming days.

### Paul Roode
> [**See my comment below.**](https://github.com/jonmenard007/SYSC4806-Project/issues/40#issuecomment-808315315)

### Rohil Dubey
**what have I done this week?**
> Linked the created DB to the web app, created user model structure, implemented user controllers for creation and logon

**what will I do next week?**
> Add views for user creation and logon, update controllers to match user model, update UML diagram, update existing views to enable functionality for more question types (choice and number)

**what is holding me back?**
> N/A

**Comment by pauliwag** [comment]
## Paul Roode

***What have I done this week?***

<table>
    <thead>
        <tr>
            <th align="left"> Description </th>
            <th align="left" width="20%"> Pull requests </th>
            <th align="left" width="20%"> Linked issues </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td> Fully implemented a service layer </td>
            <td> #42 </td>
            <td> #36 </td>
        </tr>
    </tbody>
</table>

---

***What will I do next week?***

- Further flesh out the middleware layers in support of database operations as required by the front end.
- Augment the front end with Semantic UI.
- Add and improve existing integration tests.
- Investigate the incorporation of Kafka into the project.
- Update views, scripts (e.g., Ajax), models, and tests accordingly.

---

***What is holding me back?***

Nothing - the team has done well to regularly communicate on Discord and coordinate on incrementally developing and validating the required components.
