### ISSUE TITLE
Credentials should be stored as environment variables

### ISSUE THREAD

**Issue by Jacoblab1** [jonmenard007/SYSC4806-Project#45]
I just noticed that #37 was merged recently, and that it contains the raw credentials to access our database. 

We should store our database credentials securely using environment variables in Heroku. Currently, anyone who views this repository can access our database. 

I will work to create new credentials (as these current ones are compromised) and update our application to use environment variables.

**Comment by jonmenard** [comment]
Good catch, let me know if you need any help regarding Heroku credentials

**Comment by Jacoblab1** [comment]
I've addressed this in #60, although there is still some work that needs to be done to configure Travis before we can merge it.

**Comment by Jacoblab1** [comment]
Resolved in #60
