### ISSUE TITLE
Weekly scrum - [March 20 - 26]

### ISSUE THREAD

**Issue by jonmenard** [jonmenard007/SYSC4806-Project#80]
### Jon Menard
**what have I done this week?**
> 
| Description | Pull requests|
| -- | -- |
| Added  a view to show number questions and set bounds  | #48   
| Added a controller service to set number question bounds | #48 | 
| Added a view for adding choices to choice question  | #49 | 
| Added a service to a controller for adding choices to choice question | #49 | 
| Changed surveys to produce a form of their questions, instead of a table | #50 | 
| Fixed an issue with Heroku running integration tests infinitely | #72 | 
| Fixed an issue with Spring using all available database Connections, causing IT to fail | #73  | 
| Added UI for adding an option to select questions  | #82 | 
| Added database object-relational model and updated read-me | N/A| 

**what will I do next week?**
> Next week I will be focusing on processing the results of a survey when it is closed, additionally, some routing for templates needs to be changed around and some styling needs to be fixed with CSS

**what is holding me back?**
> The Heroku issue took many hours to solve, it is resolved now but it held me back for a few days

### Jacob Laboissonniere
**what have I done this week?**
>
| Description | Pull requests|
| -- | -- |
| Migrated "Create Question" form to a separate page  | #52 
| Added ability to submit a survey response & save in DB | #53 | 
| Modified app to use environment variables for security purposes  | #60 | 
| Refactored codebase to remove unnecessary Form model  | #74 | 
| Reduced max number of connections to DB  | #75 | 
| Added ability to close a survey and view responses  | #77 | 
| Small UI fixes & styling updates  | #81 | 

**what will I do next week?**
> Will work to ensure that our application is feature-complete, and work on any final ideas we have.
Will also continue to work on tidying up styling, to ensure that it is consistent throughout the application.
Finally, will verify that all aspects of the app are properly tested.

**what is holding me back?**
> Nothing major. Had some issues with Heroku limiting the number of DB connections (which caused app to crash on launch), but that is resolved now.

### Paul Roode
> [**See my comment below.**](https://github.com/jonmenard007/SYSC4806-Project/issues/80#issuecomment-808310519)

### Rohil Dubey
**what have I done this week?**
>
| Description | Pull requests|
| -- | -- |
| Added views for user creation  | #48   
| Tested using environment variables for DB connection | #54   | 
| Added view and controller to list all open surveys  | #78  | 
| Added view and controller to fetch all surveys created by a user | #78  | 
| Updated UML Class diagram with milestone 2 progress | N/A| 

**what will I do next week?**
> Clean up web app navigation and ensure there are no dead ends, add missing integration tests, add missing unit tests, and start implementing kafka. 

**what is holding me back?**
> Finalization of the model is necessary so we can get a clear idea of all missing features.

**Comment by pauliwag** [comment]
## Paul Roode

***What have I done this week?***

<table>
    <thead>
        <tr>
            <th align="left"> Description </th>
            <th align="left" width="15%"> Pull requests </th>
            <th align="left" width="15%"> Linked issues </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan="3"> Augmented the front end with Semantic UI </td>
            <td> #79 </td>
            <td> #61 </td>
        </tr>
        <tr></tr>
        <tr>
            <td> #62 </td>
            <td> #61 </td>
        </tr>
        <tr>
            <td rowspan="3"> Added, debugged, and de-smelled integration tests </td>
            <td> #79 </td>
            <td> #59 </td>
        </tr>
        <tr></tr>
        <tr>
            <td> #55 </td>
            <td> #56 </td>
        </tr>
        <tr>
            <td rowspan="3"> Debugged, refactored, and de-smelled the middleware and DAO layers </td>
            <td> #55 </td>
            <td> #57 </td>
        </tr>
        <tr></tr>
        <tr>
            <td> #55 </td>
            <td> #58 </td>
        </tr>
    </tbody>
</table>

---

***What will I do next week?***

- Further flesh out the middleware layers in support of database operations as required by the front end.
- Finalize the UI.
- Help incorporate Kafka into the project, including the oral presentation.
- Update views, scripts (e.g., Ajax), models, and tests accordingly.

---

***What is holding me back?***

Nothing - the team has done well to regularly communicate on Discord and coordinate on incrementally developing and validating the required components.
