### ISSUE TITLE
Weekly Scrum – [Mar 27 – Apr 2]

### ISSUE THREAD

**Issue by pauliwag** [jonmenard007/SYSC4806-Project#92]
## Paul Roode

***What have I done this week?***

<table>
    <thead>
        <tr>
            <th align="left"> Description </th>
            <th align="left" width="14%"> Pull requests </th>
            <th align="left" width="14%"> Linked issues </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td> Optimized template fragments and updated integration tests accordingly </td>
            <td> #86 </td>
            <td> #87 </td>
        </tr>
        <tr>
            <td> Revamped the addQuestionChoice and changeQuestionBounds UIs using Semantic UI </td>
            <td> #86 </td>
            <td> #88 </td>
        </tr>
        <tr>
            <td rowspan="3"> Revamped the fillSurvey and viewResponses UIs using Semantic UI </td>
            <td> #89 </td>
            <td> #90 </td>
        </tr>
        <tr></tr>
        <tr>
            <td> #93 </td>
            <td> #90 </td>
        </tr>
        <tr>
            <td rowspan="3"> Improved the doSurvey UI and added measures to prevent adding/answering questions for a closed survey </td>
            <td> #89 </td>
            <td> #91 </td>
        </tr>
        <tr></tr>
        <tr>
            <td> #93 </td>
            <td> #91 </td>
        </tr>
    </tbody>
</table>

---

***What will I do next week?***

- Further flesh out the middleware layers in support of database operations as required by the front end.
- Finalize the UI.
- Help incorporate Kafka into the project, including the oral presentation.
- Update views, scripts (e.g., Ajax), models, and tests accordingly.

---

***What is holding me back?***

Nothing – the team has done well to regularly communicate on Discord and coordinate on incrementally developing and validating the required components.

**Comment by pauliwag** [comment]
## Jon Menard

***What have I done this week?***

This week most of my time was used up trying to research Kafka and find a suitable host. After trying various providers I finally found confluent.cloud that would host a cluster for our team. 

<table>
    <thead>
        <tr>
            <th align="left"> Description </th>
            <th align="left" width="14%"> Pull requests </th>
        </tr>
    </thead>
    <tbody>
   <tr>
            <td> Integrated Kafka into our application </td>
            <td> #101 </td>
        </tr>
        <tr>
            <td> Integrated Kafka logging into our system </td>
            <td> #106 </td>
        </tr>
    </tbody>
</table>

---

***What will I do next week?***

- Added statistical analysis to surveys when they are closed
- Everything else is done, we need to continue testing and fix any possible bugs

---

***What is holding me back?***

Nothing – Kafka held me back for almost 6 days, but we have figured it out now

**Comment by Jacoblab1** [comment]
## Jacob Laboissonniere

***What have I done this week?***

Worked with @jonmenard007 to research potential Kafka hosting providers for our final oral presentation. Heavy workload with other classes, so no major work was done on the main codebase. Just research & organization for our oral presentation.

---

***What will I do next week?***

- Will work more with the main codebase to improve user login functionality (by adding user sessions)
- Will add more integration tests
- Look through the codebase and refactor any problematic code

---

***What is holding me back?***

Just a heavy workload. Kafka research took a while, as we had to compare a number of different hosting providers (many of which do not offer a free plan). Now that we've got that figured out, will be able to focus more on completing our main application.
